// Conteúdo independente do motor. Números, identidades e condições ficam explícitos.
import { EXTRA_SKILLS, EXTRA_ENEMIES, EXTRA_CONTRACTS } from './expansion.js';
export const VERSION = 2;
export const GRID = 6;
export const CLASSES = {
  guard: {
    name: 'Guarda do Ossuário',
    tag: 'FERRO · CONTRA-ATAQUE',
    icon: 'shield',
    weapon: 'sword',
    hp: 50,
    vigor: 8,
    power: 0,
    skills: ['bash'],
    talents: ['sentinel'],
    text: 'Você segurou os portões até seus homens morrerem. Aparar transforma o golpe recebido em uma abertura. O escudo interrompe intenções.',
  },
  butcher: {
    name: 'Carrasco desertor',
    tag: 'SANGUE · MOBILIDADE',
    icon: 'blade',
    weapon: 'dagger',
    hp: 42,
    vigor: 9,
    power: 0,
    skills: ['lunge'],
    talents: ['bloodletter'],
    text: 'Você conhece a anatomia de quem implora. Cortes abrem sangramento; avançar encurta distâncias. Execute feridos antes que consigam responder.',
  },
  heretic: {
    name: 'Herege sem língua',
    tag: 'RITOS · SACRIFÍCIO',
    icon: 'flame',
    weapon: 'spear',
    hp: 40,
    vigor: 8,
    power: 1,
    skills: ['spark'],
    talents: ['pyromancer'],
    text: 'Você arrancou a língua tarde demais. Ainda ouve o sino. O fogo ignora parte da armadura; ritos de sangue trocam vida por alcance e poder.',
  },
};
export const WEAPONS = {
  sword: {
    name: 'Espada de vigília',
    icon: 'blade',
    damage: 9,
    range: 1,
    cost: 2,
    desc: 'Equilibrada. +3 dano ao atacar com Contra-ataque.',
    price: 28,
    scrap: 5,
  },
  dagger: {
    name: 'Facas do carrasco',
    icon: 'blade',
    damage: 6,
    range: 1,
    cost: 1,
    bleed: 2,
    desc: 'Aplica 2 Sangramento. Dano que ignora armadura a cada turno.',
    price: 28,
    scrap: 5,
  },
  maul: {
    name: 'Malho de execução',
    icon: 'hammer',
    damage: 12,
    range: 1,
    cost: 3,
    break: 1,
    desc: 'Remove 1 Armadura por golpe. Golpe pesado atordoa.',
    price: 42,
    scrap: 7,
  },
  spear: {
    name: 'Lança funerária',
    icon: 'spear',
    damage: 8,
    range: 2,
    cost: 2,
    desc: 'Alcance de 2 casas em linha reta. Ataque sem se aproximar.',
    price: 34,
    scrap: 6,
  },
  crossbow: {
    name: 'Besta de tendões',
    icon: 'bow',
    damage: 8,
    range: 5,
    cost: 3,
    desc: 'Alcance 5. Exige linha de visão. Pilares bloqueiam disparos.',
    price: 46,
    scrap: 8,
  },
};
export const ARMORS = {
  rags: {
    name: 'Mortalha',
    armor: 0,
    vigor: 1,
    desc: '+1 vigor máximo; nenhuma proteção.',
    price: 0,
  },
  leather: {
    name: 'Couro de sepultura',
    armor: 1,
    vigor: 0,
    desc: 'Reduz cada golpe em 1.',
    price: 30,
  },
  plate: {
    name: 'Placas de luto',
    armor: 3,
    vigor: -1,
    desc: 'Reduz cada golpe em 3; −1 vigor máximo.',
    price: 55,
  },
};
export const RELICS = {
  none: { name: 'Nenhuma relíquia', desc: 'Encontre relíquias nas expedições.' },
  fang: { name: 'Dente do mártir', desc: '+1 Sangramento nos cortes.', price: 45 },
  coal: {
    name: 'Coração de carvão',
    desc: 'Imune ao terreno em chamas. +2 dano de fogo.',
    price: 45,
  },
  bell: { name: 'Badalo partido', desc: 'Interromper um inimigo restaura 2 vigor.', price: 45 },
  eye: {
    name: 'Olho costurado',
    desc: 'Evitar todos os ataques de um turno restaura 3 vida.',
    price: 45,
  },
  chalice: {
    name: 'Cálice de medula',
    desc: 'Matar restaura 3 vida. Cura nunca ultrapassa o máximo.',
    price: 45,
  },
};
export const SKILLS = {
  ...EXTRA_SKILLS,
  strike: {
    name: 'Cortar',
    icon: 'blade',
    ap: 1,
    stamina: 0,
    target: 'enemy',
    desc: 'Usa o dano, alcance e custo da arma.',
  },
  heavy: {
    name: 'Golpe pesado',
    icon: 'hammer',
    ap: 2,
    stamina: 0,
    target: 'enemy',
    desc: '+7 dano, +2 vigor ao custo da arma. Malho atordoa.',
  },
  move: {
    name: 'Mover',
    icon: 'steps',
    ap: 1,
    stamina: 1,
    target: 'tile',
    desc: 'Uma casa ortogonal. Evite as casas marcadas em vermelho.',
  },
  guard: {
    name: 'Aparar',
    icon: 'shield',
    ap: 1,
    stamina: 1,
    target: 'self',
    desc: 'Bloqueia 8 dano até o próximo turno. Se bloquear: ganha Contra-ataque.',
  },
  shove: {
    name: 'Empurrar',
    icon: 'arrow',
    ap: 1,
    stamina: 2,
    target: 'enemy',
    range: 1,
    desc: '2 dano; empurra 1 casa. Colisão: +4 dano e atordoa. Abismo mata.',
  },
  flask: {
    name: 'Bálsamo',
    icon: 'flask',
    ap: 1,
    stamina: 0,
    target: 'self',
    desc: 'Consome 1 bálsamo; cura 20 vida e remove Sangramento.',
  },
  bash: {
    name: 'Ruptura',
    icon: 'shield',
    ap: 1,
    stamina: 3,
    target: 'enemy',
    range: 1,
    desc: '5 dano, remove 2 Armadura e interrompe a intenção por 1 turno.',
  },
  lunge: {
    name: 'Investida',
    icon: 'spear',
    ap: 1,
    stamina: 3,
    target: 'enemy',
    range: 3,
    desc: 'Avança até o alvo em linha reta; golpe da arma com +3 dano.',
  },
  spark: {
    name: 'Brasa',
    icon: 'flame',
    ap: 1,
    stamina: 3,
    target: 'tile',
    range: 4,
    desc: '7 dano de fogo em uma casa; incendeia óleo e casas adjacentes com óleo.',
  },
  reap: {
    name: 'Ceifar',
    icon: 'blade',
    ap: 2,
    stamina: 4,
    target: 'enemy',
    range: 1,
    desc: '12 dano + 3 por Sangramento do alvo. Consome Sangramento. Ignora armadura.',
  },
  blood: {
    name: 'Dízimo',
    icon: 'drop',
    ap: 1,
    stamina: 1,
    target: 'enemy',
    range: 4,
    desc: 'Custa 5 vida e +1 Corrupção. 11 dano arcano; ignora armadura.',
  },
  quake: {
    name: 'Quebra-ossos',
    icon: 'hammer',
    ap: 2,
    stamina: 5,
    target: 'self',
    desc: '8 dano e interrompe todos os inimigos adjacentes.',
  },
  blink: {
    name: 'Passo fúnebre',
    icon: 'steps',
    ap: 1,
    stamina: 2,
    target: 'tile',
    range: 3,
    desc: 'Move até 3 casas, atravessa unidades e pilares. Não entra em abismos.',
  },
  oil: {
    name: 'Óleo',
    icon: 'flask',
    ap: 1,
    stamina: 0,
    target: 'tile',
    range: 4,
    desc: 'Consome 1 frasco de óleo; cobre o alvo e casas ortogonais. Combine com Brasa.',
  },
  bomb: {
    name: 'Bomba',
    icon: 'burst',
    ap: 1,
    stamina: 0,
    target: 'tile',
    range: 4,
    desc: 'Consome 1 bomba; 13 dano, quebra 2 Armadura, área em cruz.',
  },
};
export const TALENTS = {
  sentinel: {
    name: 'Postura de vigília',
    path: 'Ferro',
    cost: 1,
    desc: 'Aparar bloqueia +4 dano. Contra-ataque acrescenta +5 dano.',
    requires: null,
  },
  bulwark: {
    name: 'Muralha de carne',
    path: 'Ferro',
    cost: 1,
    desc: '+8 vida máxima. Guardar custa 0 vigor.',
    requires: 'sentinel',
  },
  breaker: {
    name: 'Liturgia do impacto',
    path: 'Ferro',
    cost: 1,
    skill: 'quake',
    desc: 'Aprende Quebra-ossos, um ataque de área que cancela intenções.',
    requires: 'sentinel',
  },
  resolve: {
    name: 'Última sentinela',
    path: 'Ferro',
    cost: 2,
    desc: 'Uma vez por batalha, dano fatal deixa você com 1 vida e cancela as outras intenções.',
    requires: 'bulwark',
  },
  bloodletter: {
    name: 'Anatomia da dor',
    path: 'Sangue',
    cost: 1,
    desc: 'Todos os ataques da arma aplicam +1 Sangramento.',
    requires: null,
  },
  executioner: {
    name: 'Sentença',
    path: 'Sangue',
    cost: 1,
    skill: 'reap',
    desc: 'Aprende Ceifar: converte Sangramento em execução instantânea.',
    requires: 'bloodletter',
  },
  dancer: {
    name: 'Passo entre túmulos',
    path: 'Sangue',
    cost: 1,
    skill: 'blink',
    desc: 'Aprende Passo fúnebre: reposicionamento que atravessa obstáculos.',
    requires: 'bloodletter',
  },
  predator: {
    name: 'Fome do carrasco',
    path: 'Sangue',
    cost: 2,
    desc: 'Matar recupera 2 vigor. Ataques em inimigos com menos de metade da vida causam +4 dano.',
    requires: 'executioner',
  },
  pyromancer: {
    name: 'Fogo profano',
    path: 'Cinza',
    cost: 1,
    skill: 'spark',
    desc: 'Aprende Brasa; +2 dano em ataques de fogo.',
    requires: null,
  },
  tithe: {
    name: 'Evangelho do sangue',
    path: 'Cinza',
    cost: 1,
    skill: 'blood',
    desc: 'Aprende Dízimo. O custo de vida baixa para 3.',
    requires: 'pyromancer',
  },
  communion: {
    name: 'Comunhão',
    path: 'Cinza',
    cost: 1,
    desc: 'Usar bálsamo remove 2 Corrupção. Fogo cura você em 2 ao matar.',
    requires: 'pyromancer',
  },
  abyss: {
    name: 'Voz do abismo',
    path: 'Cinza',
    cost: 2,
    desc: 'Dízimo causa +1 dano por Corrupção, até +8. A drenagem da Corrupção começa em 9 em vez de 6.',
    requires: 'tithe',
  },
};
export const ENEMIES = {
  ...EXTRA_ENEMIES,
  husk: {
    name: 'Morto de vigília',
    glyph: 'husk',
    hp: 18,
    damage: 7,
    armor: 0,
    ai: 'melee',
    xp: 7,
    desc: 'Lento. Aproxima-se ou golpeia uma casa adjacente.',
  },
  hound: {
    name: 'Cão de vala',
    glyph: 'hound',
    hp: 14,
    damage: 6,
    armor: 0,
    ai: 'hound',
    xp: 7,
    desc: 'Salta até 2 casas. Mordida causa Sangramento.',
  },
  soldier: {
    name: 'Sentinela decapitada',
    glyph: 'soldier',
    hp: 26,
    damage: 9,
    armor: 3,
    ai: 'melee',
    xp: 10,
    desc: 'Armadura forte. Quebre-a ou use Sangramento e ritos.',
  },
  archer: {
    name: 'Besteiro costurado',
    glyph: 'archer',
    hp: 17,
    damage: 9,
    armor: 0,
    ai: 'archer',
    xp: 10,
    desc: 'Marca uma linha de disparo. Pilares bloqueiam o tiro.',
  },
  brute: {
    name: 'Carregador de cadáveres',
    glyph: 'brute',
    hp: 34,
    damage: 13,
    armor: 1,
    ai: 'brute',
    xp: 13,
    desc: 'Investida em linha; colisão com pilares o atordoa.',
  },
  cantor: {
    name: 'Cantor de medula',
    glyph: 'cantor',
    hp: 21,
    damage: 8,
    armor: 1,
    ai: 'caster',
    xp: 12,
    desc: 'Profana uma cruz de casas. Ataque adiciona Corrupção.',
  },
  leech: {
    name: 'Sanguessuga de gente',
    glyph: 'leech',
    hp: 20,
    damage: 8,
    armor: 0,
    ai: 'leech',
    xp: 10,
    desc: 'Drena vida e cura os ferimentos ao acertar.',
  },
  executioner: {
    name: 'O Açougueiro',
    glyph: 'boss',
    hp: 85,
    damage: 13,
    armor: 2,
    ai: 'bossButcher',
    xp: 48,
    boss: true,
    desc: 'Alterna guilhotina em linha, gancho e golpe em cruz. Abaixo de meia-vida, deixa sangue incendiado.',
  },
  abbess: {
    name: 'Abadessa das Moscas',
    glyph: 'boss',
    hp: 78,
    damage: 11,
    armor: 1,
    ai: 'bossAbbess',
    xp: 48,
    boss: true,
    desc: 'Círculos de praga e invocação de sanguessugas. Abaixo de meia-vida, duas cruzes são profanadas.',
  },
  warden: {
    name: 'Carcereiro sem rosto',
    glyph: 'boss',
    hp: 96,
    damage: 14,
    armor: 4,
    ai: 'bossWarden',
    xp: 52,
    boss: true,
    desc: 'Armadura pesada; esmagamento de linhas e intimidação que consome vigor.',
  },
  bellfather: {
    name: 'O Pai do Sino',
    glyph: 'boss',
    hp: 140,
    damage: 14,
    armor: 2,
    ai: 'bossBell',
    xp: 100,
    boss: true,
    desc: 'Alterna badalada em cruz, ritos e convocação. Segunda fase cobre linhas inteiras.',
  },
};
export const DISTRICTS = [
  {
    id: 'gutters',
    name: 'As Valas',
    subtitle: 'A carne ainda se lembra',
    icon: 'drop',
    color: '#ad5148',
    boss: 'executioner',
    seal: 'Selo da Carne',
    level: 1,
    terrain: 'blood',
    enemies: ['husk', 'hound', 'archer', 'brute'],
    intro:
      'Na vala comum, os mortos foram empilhados de pé. O Açougueiro costura os que tentam sair. Sua primeira língua está pendurada no portão.',
    lore: 'O Açougueiro cai. Dentro do peito dele há um badalo, não um coração. Na face interna: “Para que os mortos se levantem, primeiro é preciso que os vivos respondam.” Você reconhece sua assinatura.',
  },
  {
    id: 'abbey',
    name: 'Abadia da Fome',
    subtitle: 'Nenhuma oração alimenta',
    icon: 'flame',
    color: '#b4a66b',
    boss: 'abbess',
    seal: 'Selo da Cinza',
    level: 2,
    terrain: 'oil',
    enemies: ['leech', 'cantor', 'husk', 'archer'],
    intro:
      'As freiras dividiram a última criança em quarenta porções. Nenhuma delas morreu de fome. Agora recolhem bocas para o coro.',
    lore: 'Sob as vestes da Abadessa, centenas de bocas se calam. Seu livro diz que o sino não ressuscita ninguém. Ele obriga os corpos a repetir o último desejo. O desejo da cidade era sobreviver.',
  },
  {
    id: 'prison',
    name: 'Cárcere de Ferro',
    subtitle: 'A sentença não termina',
    icon: 'chain',
    color: '#899fa3',
    boss: 'warden',
    seal: 'Selo do Ferro',
    level: 3,
    terrain: 'pit',
    enemies: ['soldier', 'brute', 'archer', 'cantor'],
    intro:
      'As portas das celas estão abertas. Ninguém fugiu: o Carcereiro arrancou os rostos dos presos e os pendurou sobre as saídas. O seu está entre eles.',
    lore: 'O Carcereiro quebra. Sua sentença foi assinada antes da epidemia: “Fundir um sino com os nomes dos condenados.” Você não foi chamado para salvar Véspera. Foi condenado a terminar o que começou.',
  },
  {
    id: 'cathedral',
    name: 'Catedral do Badalo',
    subtitle: 'Você conhece essa voz',
    icon: 'bell',
    color: '#d1b583',
    boss: 'bellfather',
    seal: 'O Último Nome',
    level: 4,
    terrain: 'fire',
    enemies: ['soldier', 'cantor', 'leech', 'brute'],
    intro:
      'Os três selos abrem o altar. O Pai do Sino está ajoelhado. Tem suas mãos. Tem sua voz. “Eu só fiz o que você pediu”, ele diz.',
    lore: 'O Pai do Sino não implora. Quando cai, ele entrega a você o último nome que falta: o seu. O badalo para por um instante. É tempo suficiente para uma escolha.',
  },
];
export const MODIFIERS = [
  { id: 'normal', name: 'Noite sem lua', desc: 'Nenhuma regra adicional.' },
  { id: 'scarce', name: 'Velas encharcadas', desc: 'A luz cai 2 por travessia; espólios +30%.' },
  { id: 'frenzy', name: 'Procissão vermelha', desc: 'Inimigos +2 dano; espólios +30%.' },
  { id: 'iron', name: 'Luto de ferro', desc: 'Inimigos +1 Armadura; espólios +30%.' },
  { id: 'ember', name: 'Chuva de cinza', desc: 'Mais óleo e fogo no terreno; espólios +30%.' },
];
export const CONTRACTS = {
  ...EXTRA_CONTRACTS,
  rescue: {
    name: 'Uma voz no poço',
    desc: 'Encontre e resgate Mara nas Valas. A boticária passa a vender bálsamos por menos.',
    target: 1,
    reward: 35,
  },
  relic: {
    name: 'Os dentes da santa',
    desc: 'Recupere três relicários em eventos ou tesouros. Libera o Cálice de medula.',
    target: 3,
    reward: 50,
  },
  hunt: {
    name: 'A conta dos mortos',
    desc: 'Mate doze criaturas. O ferreiro concede material e abre a melhoria III.',
    target: 12,
    reward: 25,
  },
};
export const EVENTS = {
  well: {
    name: 'O poço de Mara',
    text: 'Uma voz pede que você não corte a corda. Há mãos demais segurando a menina lá embaixo.',
    district: 0,
    choices: [
      {
        label: 'Descer e cortar as mãos',
        hint: '−7 vida · resgata Mara · +reputação',
        effect: 'rescue',
      },
      {
        label: 'Pagar ao vigia',
        hint: '−20 ossos · resgata Mara sem ferimento',
        effect: 'rescuePay',
      },
      {
        label: 'Retirar a corda e seguir',
        hint: '+1 corda de vela (3 luz) · Mara permanece',
        effect: 'abandon',
      },
    ],
  },
  marrow: {
    name: 'Ossos rachados',
    text: 'Um mercador morto segura uma bolsa entre as costelas. Os dentes dele batem quando você se aproxima.',
    choices: [
      { label: 'Quebrar as costelas', hint: '+18 ossos · −4 vida', effect: 'bones' },
      { label: 'Recolher só o material solto', hint: '+3 sucata · sem risco', effect: 'scrap' },
      { label: 'Queimar o cadáver', hint: '−1 luz · −2 Corrupção', effect: 'cleanse' },
    ],
  },
  altar: {
    name: 'Um altar ainda quente',
    text: 'O altar guarda um resto de calor humano. Um nome está escrito no carvão. Você consegue apagá-lo, se usar o seu próprio sangue.',
    choices: [
      {
        label: 'Oferecer sangue',
        hint: '−6 vida · +1 ponto de talento · +2 Corrupção · uma vez por distrito',
        effect: 'altar',
      },
      { label: 'Desmantelar o altar', hint: '+5 sucata · +1 relicário', effect: 'dismantle' },
      { label: 'Lembrar o nome', hint: '−2 Corrupção · +8 experiência', effect: 'remember' },
    ],
  },
  survivor: {
    name: 'Os que sobraram',
    text: 'Três sobreviventes bebem água do chão. Um segura uma faca contra a própria garganta. Pedem uma única dose do seu bálsamo.',
    choices: [
      {
        label: 'Dividir um bálsamo',
        hint: '−1 bálsamo · +2 reputação · +20 ossos',
        effect: 'giveFlask',
      },
      {
        label: 'Escoltar pelo túnel',
        hint: '−2 luz · +1 reputação · +12 experiência',
        effect: 'escort',
      },
      { label: 'Seguir sem prometer', hint: 'Nenhum recurso gasto', effect: 'leave' },
    ],
  },
  shrine: {
    name: 'Santo sem olhos',
    text: 'Uma estátua chora piche. Aos pés dela, moedas e um dente fresco. As pálpebras de pedra parecem recém-costuradas.',
    choices: [
      { label: 'Tomar o dente', hint: 'Relíquia Dente do mártir · +2 Corrupção', effect: 'fang' },
      { label: 'Lavar a estátua', hint: '−10 ossos · −3 Corrupção · cura 10', effect: 'wash' },
      { label: 'Arrancar os olhos de pedra', hint: '+1 relicário · +3 sucata', effect: 'relic' },
    ],
  },
  trap: {
    name: 'O corredor dos fios',
    text: 'Fios quase invisíveis atravessam o corredor. Um homem está suspenso por eles, ainda vivo. Suas pernas já tocaram o chão.',
    choices: [
      { label: 'Cortar com cuidado', hint: '−1 luz · +1 bomba · +4 sucata', effect: 'disarm' },
      { label: 'Abrir caminho à força', hint: '−8 vida · +15 ossos', effect: 'force' },
      { label: 'Voltar pelo ossário', hint: '−2 luz · sem ferimento', effect: 'detour' },
    ],
  },
  confession: {
    name: 'Confessionário',
    text: 'Do outro lado da grade, alguém fala com a voz da sua mãe. Ela pergunta quantos nomes você colocou no metal.',
    choices: [
      { label: 'Confessar', hint: '+2 Corrupção · +18 experiência', effect: 'confess' },
      { label: 'Queimar a grade', hint: '−1 luz · −2 Corrupção', effect: 'cleanse' },
      { label: 'Não responder', hint: 'Cura 5 · sem Corrupção', effect: 'silence' },
    ],
  },
  surgeon: {
    name: 'O cirurgião cego',
    text: 'Ele costura sem enxergar. Reconhece suas cicatrizes pelo cheiro. “Uma dívida de carne pode ser paga com metal.”',
    choices: [
      {
        label: 'Remover uma cicatriz',
        hint: '−25 ossos · −1 ferimento · cura 12',
        effect: 'surgery',
      },
      { label: 'Comprar bálsamo concentrado', hint: '−12 ossos · +1 bálsamo', effect: 'buyFlask' },
      { label: 'Entregar material', hint: '−4 sucata · cura 16', effect: 'patch' },
    ],
  },
  funeral: {
    name: 'Funeral de ninguém',
    text: 'Seis caixões, seis nomes riscados. Um deles contém a lança de uma sentinela. Outro vibra no ritmo do sino.',
    choices: [
      {
        label: 'Abrir o caixão da lança',
        hint: 'Recebe Lança funerária · +1 Corrupção',
        effect: 'spear',
      },
      { label: 'Abrir o que vibra', hint: '+1 relicário · +18 ossos · −6 vida', effect: 'coffin' },
      { label: 'Enterrar os seis', hint: '−1 luz · +1 reputação · −2 Corrupção', effect: 'bury' },
    ],
  },
  pyre: {
    name: 'Pira de óleo',
    text: 'Uma centena de corpos encharcados de óleo bloqueia a passagem. No centro, um coração de carvão ainda pulsa.',
    choices: [
      { label: 'Retirar o coração', hint: 'Relíquia Coração de carvão · −8 vida', effect: 'coal' },
      { label: 'Encher seus frascos', hint: '+2 óleo · +1 bomba', effect: 'oil' },
      {
        label: 'Acender e esperar',
        hint: '−2 luz · +10 experiência · −2 Corrupção',
        effect: 'pyre',
      },
    ],
  },
  chained: {
    name: 'O prisioneiro do portão',
    text: 'Uma corrente atravessa o peito do preso. Ele oferece a chave em troca de uma promessa: que seu corpo não seja levado para a catedral.',
    district: 2,
    choices: [
      {
        label: 'Cumprir sua última vontade',
        hint: '+5 sucata · +1 reputação · −5 vida',
        effect: 'mercy',
      },
      { label: 'Tomar a chave', hint: '+25 ossos · +2 Corrupção', effect: 'key' },
      {
        label: 'Romper as correntes',
        hint: '−4 sucata · +1 relicário · +15 experiência',
        effect: 'free',
      },
    ],
  },
  choir: {
    name: 'Ensaio do coro',
    text: 'Bocas penduradas cantam seu nome. Uma pausa entre as notas permite passar, mas um dos dentes guarda um fragmento do relicário.',
    district: 3,
    choices: [
      { label: 'Passar na pausa', hint: '−1 luz · +12 experiência', effect: 'quiet' },
      {
        label: 'Arrancar o fragmento',
        hint: '+1 relicário · −7 vida · +1 Corrupção',
        effect: 'fragment',
      },
      { label: 'Responder ao coro', hint: '+25 experiência · +3 Corrupção', effect: 'answer' },
    ],
  },
};
export const NODE_TYPES = {
  battle: {
    name: 'Confronto',
    icon: 'blade',
    desc: 'Enfrente a congregação. Ganhe ossos, sucata e experiência.',
  },
  elite: {
    name: 'Caçada',
    icon: 'skull',
    desc: 'Mais inimigos e armadura. Espólios maiores e uma relíquia.',
  },
  event: {
    name: 'Vestígio',
    icon: 'eye',
    desc: 'Uma escolha com consequências. Nenhum combate obrigatório.',
  },
  cache: {
    name: 'Relicário',
    icon: 'chest',
    desc: 'Material, provisões ou equipamento. Escolha o que carregar.',
  },
  camp: {
    name: 'Abrigo',
    icon: 'camp',
    desc: 'Recupere vida, luz ou retire Corrupção. O custo é a outra oportunidade.',
  },
  merchant: {
    name: 'Contrabandista',
    icon: 'coins',
    desc: 'Troque espólios por recursos ou uma relíquia.',
  },
  boss: {
    name: 'Guardião do selo',
    icon: 'bell',
    desc: 'Um inimigo único guarda a passagem. A derrota dele muda a cidade.',
  },
};
