// A Congregação — encontros e sistemas da expansão. Nenhum serviço externo.
export const RUNES = {
  none: {
    name: 'Sem gravação',
    desc: 'A arma preserva suas propriedades originais.',
    damage: 0,
    vigor: 0,
    cost: { bones: 0, scrap: 0, ichor: 0 },
  },
  blood: {
    name: 'Fio de sangue',
    desc: 'Ataques da arma aplicam +2 Sangramento, mas custam +1 vigor. Converte golpes curtos em feridas persistentes.',
    damage: 0,
    vigor: 1,
    cost: { bones: 25, scrap: 5, ichor: 0 },
  },
  frost: {
    name: 'Sal de inverno',
    desc: '−2 dano da arma. Ataques interrompem intenções de movimento; não interrompem golpes ou invocações.',
    damage: -2,
    vigor: 0,
    cost: { bones: 30, scrap: 7, ichor: 1 },
  },
  ember: {
    name: 'Marca da pira',
    desc: 'Golpe pesado incendeia uma cruz no impacto, com 4 dano de fogo por alvo. Também espalha fogo pelo óleo conectado.',
    damage: 0,
    vigor: 0,
    cost: { bones: 35, scrap: 6, ichor: 1 },
  },
  hunger: {
    name: 'Boca de ferro',
    desc: '−2 dano da arma. Cada ataque da arma que acerta recupera 3 vida. Curar-se exige entrar no alcance da arma.',
    damage: -2,
    vigor: 0,
    cost: { bones: 30, scrap: 8, ichor: 1 },
  },
  echo: {
    name: 'Eco da sentinela',
    desc: 'Contra-ataques causam +3 dano e interrompem a intenção do alvo. Prepare um aparo antes de atacar.',
    damage: 0,
    vigor: 0,
    cost: { bones: 40, scrap: 5, ichor: 2 },
  },
  salt: {
    name: 'Nome queimado',
    desc: '+3 dano de fogo e Dízimo. Dízimo adiciona +2 Corrupção em vez de +1: poder agora, purificação depois.',
    damage: 0,
    vigor: 0,
    cost: { bones: 35, scrap: 8, ichor: 1 },
  },
};
export const COMPANIONS = {
  mara: {
    name: 'Mara, a boticária',
    icon: 'flask',
    skill: 'suture',
    require: 'rescue',
    desc: 'Uma ordem por combate: cura 12 vida e remove Sangramento, gastando 1 ação. Resgate-a no poço das Valas.',
  },
  ivo: {
    name: 'Ivo, o acorrentado',
    icon: 'chain',
    skill: 'hook',
    require: 'ivo',
    desc: 'Uma ordem por combate: puxa um inimigo, causa 4 dano e remove 1 Armadura. Colisão interrompe. Liberte-o em um encontro de resgate.',
  },
  sibyl: {
    name: 'Sibila, a voz quebrada',
    icon: 'bell',
    skill: 'silence',
    require: 'silence',
    desc: 'Uma ordem por combate: interrompe um rito, cura ou invocação à distância; causa 6 dano arcano e +1 Corrupção. Cumpra o contrato do coro.',
  },
};
export const EXTRA_SKILLS = {
  interact: {
    name: 'Interagir',
    icon: 'hand',
    ap: 1,
    stamina: 1,
    target: 'tile',
    range: 1,
    desc: 'Adjacente: rompe uma âncora, abre uma jaula ou recolhe provisões. Casas vazias não são alvos válidos.',
  },
  suture: {
    name: 'Sutura',
    icon: 'flask',
    ap: 1,
    stamina: 0,
    target: 'self',
    desc: 'Mara cura 12 vida e remove Sangramento. Consome a única ordem da companhia neste combate.',
  },
  hook: {
    name: 'Correntes',
    icon: 'chain',
    ap: 1,
    stamina: 2,
    target: 'enemy',
    range: 3,
    desc: 'Ivo puxa o alvo uma casa, remove 1 Armadura e causa 4 dano. Colisão: +4 dano e interrupção. Uma ordem por combate.',
  },
  silence: {
    name: 'Silenciar',
    icon: 'bell',
    ap: 1,
    stamina: 3,
    target: 'enemy',
    range: 4,
    desc: 'Sibila interrompe uma intenção de rito, cura ou invocação, causa 6 dano arcano e adiciona 1 Corrupção. Uma ordem por combate.',
  },
};
export const EXTRA_ENEMIES = {
  bulwark: {
    name: 'Portador de lápides',
    glyph: 'bulwark',
    hp: 29,
    damage: 8,
    armor: 2,
    ai: 'melee',
    xp: 13,
    role: 'ward',
    desc: 'Protege outros inimigos adjacentes: reduz em 3 o dano físico recebido por eles. Fogo, Sangramento e ritos atravessam essa proteção. Separe o grupo ou mate o portador.',
  },
  stitcher: {
    name: 'Costureira de nervos',
    glyph: 'stitcher',
    hp: 19,
    damage: 6,
    armor: 0,
    ai: 'healer',
    xp: 13,
    desc: 'Se houver um aliado ferido, anuncia uma cura de 9 vida. A intenção pode ser interrompida. Sem feridos, profana uma cruz.',
  },
  bomber: {
    name: 'Penitente de pólvora',
    glyph: 'bomber',
    hp: 16,
    damage: 14,
    armor: 0,
    ai: 'bomber',
    xp: 11,
    desc: 'Aproxima-se duas casas; perto de você anuncia uma detonação em cruz. A explosão mata o penitente, quebra armadura e incendeia óleo. Interromper cancela a detonação.',
  },
  gaoler: {
    name: 'Arrastador de correntes',
    glyph: 'gaoler',
    hp: 23,
    damage: 8,
    armor: 1,
    ai: 'gaoler',
    xp: 12,
    desc: 'Arremessa correntes em linha. Se acertar, seu próximo movimento custa +2 vigor. O custo aparece antes de confirmar; aparar ou evitar o golpe impede o acerto.',
  },
};
export const OBJECTIVES = {
  eliminate: { name: 'Romper a congregação', desc: 'Derrote todos os inimigos.', icon: 'blade' },
  ritual: {
    name: 'Âncoras do ritual',
    desc: 'Rompa duas âncoras adjacente com Interagir, ou derrote todos. Romper ambas encerra o ritual e dá bônus.',
    icon: 'bell',
  },
  rescue: {
    name: 'Uma vida nas correntes',
    desc: 'Liberte o prisioneiro com Interagir antes do fim do confronto. Ele sofre ataques de área e fogo. O resgate é opcional.',
    icon: 'chain',
  },
  supplies: {
    name: 'Provisões sob fogo',
    desc: 'Use Interagir junto do baú para obter um bálsamo e uma bomba antes do fim do confronto. Saquear é opcional.',
    icon: 'chest',
  },
  siege: {
    name: 'A porta deve resistir',
    desc: 'Resista por seis turnos. Reforços chegam nos turnos 3 e 5. Depois, termine junto da saída e use Interagir para fugir.',
    icon: 'shield',
  },
};
export const LAYOUTS = {
  ruins: { name: 'Ruína aberta', walls: ['1,2', '4,3'], pits: [], oil: [] },
  corridor: {
    name: 'Corredor de execução',
    walls: ['1,1', '1,2', '1,3', '4,1', '4,2', '4,3'],
    pits: [],
    oil: [],
  },
  pyre: {
    name: 'Pira dos desmembrados',
    walls: ['0,3', '5,3'],
    pits: [],
    oil: ['1,2', '2,2', '3,2', '4,2', '2,3', '3,3'],
  },
  bridge: {
    name: 'Ponte de sepultura',
    walls: ['0,2', '5,2'],
    pits: ['0,3', '1,3', '4,3', '5,3'],
    oil: [],
  },
  crypt: { name: 'Cripta dos nomes', walls: ['1,2', '3,2', '4,4'], pits: [], oil: [] },
  altar: { name: 'Círculo do coro', walls: ['1,3', '4,3'], pits: [], oil: ['2,2', '3,2'] },
};
export const ENCOUNTERS = {
  gutters_pack: {
    name: 'A matilha da vala',
    district: 'gutters',
    layout: 'ruins',
    foes: ['hound', 'hound', 'husk'],
    objective: 'eliminate',
    desc: 'Cães rápidos cercam um morto lento. Espere o salto antes de avançar.',
  },
  gutters_pyre: {
    name: 'Pólvora entre corpos',
    district: 'gutters',
    layout: 'pyre',
    foes: ['bomber', 'archer', 'husk'],
    objective: 'supplies',
    desc: 'Um penitente e um besteiro guardam as provisões. A pólvora transforma óleo em uma armadilha.',
  },
  gutters_ritual: {
    name: 'O batismo da carne',
    district: 'gutters',
    layout: 'altar',
    foes: ['cantor', 'hound', 'husk'],
    objective: 'ritual',
    desc: 'Dois sinos pequenos sustentam o ritual. Escolha entre matar e romper as âncoras.',
  },
  gutters_rescue: {
    name: 'A jaula no ossário',
    district: 'gutters',
    layout: 'crypt',
    foes: ['husk', 'archer', 'gaoler'],
    objective: 'rescue',
    desc: 'Um acorrentado tenta cobrir o próprio nome. Ataques de área podem matá-lo antes de você chegar.',
  },
  abbey_choir: {
    name: 'Coro protegido',
    district: 'abbey',
    layout: 'altar',
    foes: ['cantor', 'bulwark', 'leech'],
    objective: 'ritual',
    desc: 'A lápide protege o cantor. Ritos e Sangramento atravessam sua defesa.',
  },
  abbey_surgeon: {
    name: 'Costuras que andam',
    district: 'abbey',
    layout: 'crypt',
    foes: ['stitcher', 'leech', 'husk'],
    objective: 'eliminate',
    desc: 'A costureira repara os feridos. Interrompa a cura ou concentre o dano.',
  },
  abbey_pyre: {
    name: 'O refeitório incendiado',
    district: 'abbey',
    layout: 'pyre',
    foes: ['bomber', 'leech', 'cantor'],
    objective: 'supplies',
    desc: 'Há provisões entre o óleo. Uma detonação pode atingir os dois lados.',
  },
  abbey_siege: {
    name: 'Porta do refeitório',
    district: 'abbey',
    layout: 'corridor',
    foes: ['husk', 'leech'],
    objective: 'siege',
    desc: 'Segure a passagem até poder sair. As bocas do coro chamarão reforços.',
  },
  prison_guard: {
    name: 'A última escolta',
    district: 'prison',
    layout: 'bridge',
    foes: ['bulwark', 'soldier', 'archer'],
    objective: 'eliminate',
    desc: 'Uma formação blindada sobre abismos. Separe a escolta ou use o precipício.',
  },
  prison_rescue: {
    name: 'A sentença de Ivo',
    district: 'prison',
    layout: 'crypt',
    foes: ['gaoler', 'soldier', 'archer'],
    objective: 'rescue',
    desc: 'Ivo conhece o peso das correntes. Liberte-o antes de encerrar o confronto.',
  },
  prison_siege: {
    name: 'Motim sem rostos',
    district: 'prison',
    layout: 'corridor',
    foes: ['gaoler', 'husk'],
    objective: 'siege',
    desc: 'Correntes dificultam a retirada. Ondas chegam antes de a porta abrir.',
  },
  cathedral_chorus: {
    name: 'A geometria do nome',
    district: 'cathedral',
    layout: 'altar',
    foes: ['cantor', 'stitcher', 'bulwark'],
    objective: 'ritual',
    desc: 'Proteção e cura sustentam o cantor. As âncoras oferecem outra saída.',
  },
  cathedral_guard: {
    name: 'A guarda do badalo',
    district: 'cathedral',
    layout: 'bridge',
    foes: ['soldier', 'bulwark', 'gaoler'],
    objective: 'eliminate',
    desc: 'A congregação aprendeu a proteger os seus. Seu posicionamento desmonta a formação.',
  },
  cathedral_siege: {
    name: 'O átrio dos últimos vivos',
    district: 'cathedral',
    layout: 'corridor',
    foes: ['leech', 'cantor'],
    objective: 'siege',
    desc: 'O coro cerca a porta. Resista, abra caminho e alcance a saída.',
  },
  cathedral_pyre: {
    name: 'O nome na pólvora',
    district: 'cathedral',
    layout: 'pyre',
    foes: ['bomber', 'stitcher', 'brute'],
    objective: 'supplies',
    desc: 'Uma costureira, uma carga de pólvora e um carregador. Mire nas relações entre eles.',
  },
};
export const EXTRA_CONTRACTS = {
  ivo: {
    name: 'O peso das correntes',
    desc: 'Liberte um prisioneiro em um encontro de resgate. Ivo passa a acompanhar suas expedições.',
    target: 1,
    reward: 35,
  },
  silence: {
    name: 'Um lugar para o silêncio',
    desc: 'Mate seis cantores, costureiras ou arrastadores. Sibila aprende a romper os ritos do coro.',
    target: 6,
    reward: 45,
  },
};
